### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rauschma** [rbuckton/regexp-match-indices#1]
The following code doesn’t seem to work:

```js
require('regexp-match-indices/auto');
require('regexp-match-indices').config.mode = 'spec-compliant';

const regExp = /(a+)(b+)/g;
let match;
while (match = regExp.exec('aabbb aaaab')) {
  console.dir(match);
}

// RangeError: Maximum call stack size exceeded
```

Node.js 13.3.0

**Comment by ljharb** [comment]
what happens if you `console.log` it instead of `console.dir`?

**Comment by rauschma** [comment]
Same:

```
RangeError: Maximum call stack size exceeded
    at RegExp.get flags [as flags] (<anonymous>)
    at getMeasurementRegExp (/Users/rauschma/tmp/node_modules/regexp-match-indices/implementation.js:79:98)
    at execSpecCompliant (/Users/rauschma/tmp/node_modules/regexp-match-indices/implementation.js:59:47)
    at RegExp.exec (/Users/rauschma/tmp/node_modules/regexp-match-indices/implementation.js:27:11)
    at RegExp.[Symbol.match] (<anonymous>)
    at String.match (<anonymous>)
    at Object._match (/Users/rauschma/tmp/node_modules/regexp-tree/dist/parser/generated/regexp-tree.js:683:26)
    at Object.getNextToken (/Users/rauschma/tmp/node_modules/regexp-tree/dist/parser/generated/regexp-tree.js:568:26)
    at Object.parse (/Users/rauschma/tmp/node_modules/regexp-tree/dist/parser/generated/regexp-tree.js:769:27)
    at Object.regexpTreeParser.parse (/Users/rauschma/tmp/node_modules/regexp-tree/dist/parser/index.js:22:10)
```
