### ISSUE TITLE
SyntaxError: Invalid flags: d

### ISSUE THREAD

**Issue by Enteleform** [rbuckton/regexp-match-indices#15]
Currently getting this stack trace when I try to consume a compiled library that uses `regexp-match-indices`:

```log
SyntaxError: Invalid flags: d
  at checkFlags                    \regexp-tree\dist\parser\generated\regexp-tree.js:1148:15
  at Array.productions             \regexp-tree\dist\parser\generated\regexp-tree.js:82:12
  at Object.parse                  \regexp-tree\dist\parser\generated\regexp-tree.js:846:27
  at Object.regexpTreeParser.parse \regexp-tree\dist\parser\index.js:22:10
  at Object.parse                  \regexp-tree\dist\regexp-tree.js:57:19
  at getMeasurementRegExp          \regexp-match-indices\implementation.ts:103:50
  at Array.get [as indices]        \regexp-match-indices\implementation.ts:62:59
```

The code works fine when I run it in the library via `ts-node`, but once the library is compiled via `tsc` and I import it into another project, the issue occurs.

I've tried executing the consuming code via `ts-node`, `tsc && node`,  and `node  --loader ts-node/esm`; but nothing has worked so far.

**Comment by zimonitrome** [comment]
I also get this error. For me it occurs in a really weird manner when I am writing a VSCode extension. The extension named "Todo Tree" uses this polyfill and the library usage seemingly spreads to other extensions too, even though the actual es2022 behavior is already implemented in VSCode.

@Enteleform did you find a fix for this?

**Comment by rokas-th** [comment]
Root cause, for anyone still hitting this: the feature detection in `getPolyfill()` tests for `indices` on a regex that has no `d` flag, so it can never detect native support and the polyfill is installed on **every** engine, including ones that implement the proposal natively.

The detect (v1.0.2) reduces to:

```js
const re = new RegExp("a");
return native.call(re, "a").indices ? native : polyfill;
```

But `indices` only exists on a match when the regex itself carries `d`:

```js
new RegExp("a").exec("a").indices       // undefined   <- what the detect sees
new RegExp("a", "d").exec("a").indices  // [ [ 0, 1 ] ]
```

(measured on Node 24 and in the VS Code 1.138 / Electron 42 extension host, both of which have native support)

So `getPolyfill()` always returns the polyfill, and `shim()`:

```js
const impl = getPolyfill();
if (RegExp.prototype.exec !== impl) RegExp.prototype.exec = impl;
```

unconditionally replaces `RegExp.prototype.exec` **process-wide**. Every match in the process then carries the polyfill's `indices` getter, which re-parses `/source/flags` through `regexp-tree`, whose `checkFlags` only accepts `gimsuxy`. Any consumer regex using the `d` flag therefore throws `SyntaxError: Invalid flags: …` — which is why the error appears with a `d` in it while the code that threw is this package.

One-character fix, giving the detect a regex that can actually carry the property:

```js
const re = new RegExp("a", "d");
```

Native is then selected on a supporting engine, and `shim()` becomes a no-op because `RegExp.prototype.exec === impl`.

### Why this hits unrelated code

@zimonitrome's observation about it "spreading to other extensions" is exactly this. VS Code runs all extensions in one shared extension host process, and Todo Tree calls `.shim()` at module load, so the global `exec` replacement is visible to every other extension in that process. Concretely: the Inertia extension's document-link provider uses `/…/dgm` regexes and its links stop working entirely, with the stack pointing into Todo Tree's bundle rather than its own.

Patching the detect locally in Todo Tree's bundle fixes it. Verified by reproducing the failure on demand in a running window, restarting, and failing to reproduce it against the same file — on both macOS and Linux.

Worth noting the trade-off for consumers that rely on the shim: with native `exec` restored, `indices` is `undefined` unless their own regex carries `d`, which is correct per the proposal but is a behaviour change for anyone who was (unknowingly) depending on the polyfill supplying indices for non-`d` regexes.
